In [24]:
import requests
import pandas as pd

## **2. Obtenci√≥n de los datos**

In [25]:
#Apple
# Se lee un archivo .txt donde se encuentra el key privado de la API
with open("InfoIgnore/pass.txt",'r') as f:
    pwd= f.read()
# Se lee el API, se genera el requests y se descargan los datos de la API
url1 = "https://api.polygon.io/v2/aggs/ticker/AAPL/range/1/week/2022-01-01/2022-12-31?adjusted=true&sort=asc&apiKey="+pwd
headers1 = {"Accept-Encoding": "gzip, deflate"}
response1 = requests.get(url1, headers=headers1)
Apple = response1.json()
print(response1)
print(Apple)
Apple.keys()

<Response [200]>
{'ticker': 'AAPL', 'queryCount': 256, 'resultsCount': 53, 'adjusted': True, 'results': [{'v': 339980123.0, 'vw': 179.0995, 'o': 177.085, 'c': 177.57, 'h': 181.33, 'l': 177.07, 't': 1640494800000, 'n': 2704014}, {'v': 481915611.0, 'vw': 177.1385, 'o': 177.83, 'c': 172.17, 'h': 182.94, 'l': 171.03, 't': 1641099600000, 'n': 4130315}, {'v': 422544574.0, 'vw': 173.0033, 'o': 169.08, 'c': 173.07, 'h': 177.18, 'l': 168.17, 't': 1641704400000, 'n': 3613640}, {'v': 400124342.0, 'vw': 167.1724, 'o': 171.51, 'c': 162.41, 'h': 172.54, 'l': 162.3, 't': 1642309200000, 'n': 3479982}, {'v': 688149428.0, 'vw': 161.9512, 'o': 160.02, 'c': 170.33, 'h': 170.35, 'l': 154.7, 't': 1642914000000, 'n': 6337774}, {'v': 457896933.0, 'vw': 173.6787, 'o': 170.16, 'c': 172.39, 'h': 176.2399, 'l': 169.51, 't': 1643518800000, 'n': 3772842}, {'v': 412491545.0, 'vw': 172.9816, 'o': 172.86, 'c': 168.64, 'h': 176.65, 'l': 168.04, 't': 1644123600000, 'n': 3357351}, {'v': 363973562.0, 'vw': 169.7229, 'o': 167.37, 'c': 167.3, 'h': 173.34, 'l': 166.19, 't': 1644728400000, 'n': 3135169}, {'v': 414279367.0, 'vw': 161.6358, 'o': 164.98, 'c': 164.85, 'h': 166.69, 'l': 152, 't': 1645333200000, 'n': 3913514}, {'v': 418748277.0, 'vw': 164.8511, 'o': 163.06, 'c': 163.17, 'h': 168.91, 'l': 161.97, 't': 1645938000000, 'n': 3604858}, {'v': 521263065.0, 'vw': 159.1796, 'o': 163.36, 'c': 154.73, 'h': 165.02, 'l': 154.5, 't': 1646542800000, 'n': 4483479}, {'v': 502202118.0, 'vw': 157.0603, 'o': 151.45, 'c': 163.98, 'h': 164.48, 'l': 150.1, 't': 1647147600000, 'n': 3865367}, {'v': 446066807.0, 'vw': 169.9039, 'o': 163.51, 'c': 174.72, 'h': 175.28, 'l': 163.015, 't': 1647748800000, 'n': 3496251}, {'v': 462473123.0, 'vw': 176.0361, 'o': 172.17, 'c': 174.31, 'h': 179.61, 'l': 171.94, 't': 1648353600000, 'n': 3565345}, {'v': 393135409.0, 'vw': 173.4356, 'o': 174.57, 'c': 170.09, 'h': 178.49, 'l': 169.2, 't': 1648958400000, 'n': 3264600}, {'v': 297200188.0, 'vw': 167.9104, 'o': 168.71, 'c': 165.29, 'h': 171.27, 'l': 165.04, 't': 1649563200000, 'n': 2510591}, {'v': 376780780.0, 'vw': 166.3952, 'o': 163.92, 'c': 161.79, 'h': 171.53, 'l': 161.5, 't': 1650168000000, 'n': 3202178}, {'v': 541572480.0, 'vw': 160.0844, 'o': 161.12, 'c': 157.65, 'h': 166.2, 'l': 155.38, 't': 1650772800000, 'n': 4761186}, {'v': 566136906.0, 'vw': 158.4409, 'o': 156.71, 'c': 157.28, 'h': 166.48, 'l': 153.27, 't': 1651377600000, 'n': 4922732}, {'v': 685891225.0, 'vw': 148.5733, 'o': 154.925, 'c': 147.11, 'h': 156.74, 'l': 138.8, 't': 1651982400000, 'n': 6001720}, {'v': 547781090.0, 'vw': 141.4217, 'o': 145.55, 'c': 137.59, 'h': 149.77, 'l': 132.61, 't': 1652587200000, 'n': 4644378}, {'v': 496367915.0, 'vw': 142.178, 'o': 137.79, 'c': 149.64, 'h': 149.68, 'l': 137.14, 't': 1653192000000, 'n': 3708891}, {'v': 338923395.0, 'vw': 148.3911, 'o': 149.07, 'c': 145.38, 'h': 151.74, 'l': 144.46, 't': 1653796800000, 'n': 2671650}, {'v': 354396344.0, 'vw': 144.6664, 'o': 147.03, 'c': 137.13, 'h': 149.8697, 'l': 137.06, 't': 1654401600000, 'n': 2947108}, {'v': 540927195.0, 'vw': 132.3553, 'o': 132.87, 'c': 131.56, 'h': 137.34, 'l': 129.04, 't': 1655006400000, 'n': 4081442}, {'v': 315245327.0, 'vw': 137.5794, 'o': 133.42, 'c': 141.66, 'h': 141.91, 'l': 133.32, 't': 1655611200000, 'n': 2232249}, {'v': 373781666.0, 'vw': 138.7296, 'o': 142.695, 'c': 138.93, 'h': 143.49, 'l': 133.7737, 't': 1656216000000, 'n': 2904354}, {'v': 278291202.0, 'vw': 143.5107, 'o': 137.77, 'c': 147.04, 'h': 147.55, 'l': 136.93, 't': 1656820800000, 'n': 2247819}, {'v': 366480107.0, 'vw': 146.7215, 'o': 145.67, 'c': 150.17, 'h': 150.86, 'l': 142.1201, 't': 1657425600000, 'n': 2800167}, {'v': 360913157.0, 'vw': 151.8343, 'o': 150.74, 'c': 154.09, 'h': 156.28, 'l': 146.7, 't': 1658030400000, 'n': 2770521}, {'v': 370443015.0, 'vw': 156.8445, 'o': 154.01, 'c': 162.51, 'h': 163.63, 'l': 150.8, 't': 1658635200000, 'n': 3050946}, {'v': 322364021.0, 'vw': 163.6249, 'o': 161.01, 'c': 165.35, 'h': 167.19, 'l': 159.63, 't': 1659240000000, 'n': 2836942}, {'v': 318789872.0, 'vw': 167.9554, 'o': 166.37, 'c': 172.1, 'h': 172.17, 'l': 163.25, 't': 1659844800000, 'n': 2645896}, {'v': 322637851.0, 'vw': 173.2677, 'o': 171.52, 'c': 171.52, 'h': 176.15, 'l': 171.3101, 't': 1660449600000, 'n': 2822117}, {'v': 307143601.0, 'vw': 167.5844, 'o': 169.69, 'c': 163.62, 'h': 171.05, 'l': 163.56, 't': 1661054400000, 'n': 2779862}, {'v': 390248905.0, 'vw': 158.6627, 'o': 161.145, 'c': 155.81, 'h': 162.9, 'l': 154.67, 't': 1661659200000, 'n': 3193172}, {'v': 313999120.0, 'vw': 155.2847, 'o': 156.47, 'c': 157.37, 'h': 157.82, 'l': 152.68, 't': 1662264000000, 'n': 2614505}, {'v': 566964166.0, 'vw': 155.0026, 'o': 159.59, 'c': 150.7, 'h': 164.26, 'l': 148.37, 't': 1662868800000, 'n': 4127179}, {'v': 473493283.0, 'vw': 153.6606, 'o': 149.31, 'c': 150.43, 'h': 158.74, 'l': 148.56, 't': 1663473600000, 'n': 3702910}, {'v': 577332048.0, 'vw': 146.2906, 'o': 149.66, 'c': 138.2, 'h': 154.72, 'l': 138, 't': 1664078400000, 'n': 4588443}, {'v': 435595923.0, 'vw': 143.4892, 'o': 138.21, 'c': 140.09, 'h': 147.54, 'l': 137.685, 't': 1664683200000, 'n': 3337281}, {'v': 423656562.0, 'vw': 139.7221, 'o': 140.42, 'c': 138.38, 'h': 144.52, 'l': 134.37, 't': 1665288000000, 'n': 3346749}, {'v': 397209509.0, 'vw': 143.8543, 'o': 141.065, 'c': 147.27, 'h': 147.8479, 'l': 140.27, 't': 1665892800000, 'n': 3070678}, {'v': 512472221.0, 'vw': 150.451, 'o': 147.185, 'c': 155.74, 'h': 157.5, 'l': 144.13, 't': 1666497600000, 'n': 4101362}, {'v': 510328201.0, 'vw': 145.0799, 'o': 153.155, 'c': 138.38, 'h': 155.45, 'l': 134.38, 't': 1667102400000, 'n': 4199269}, {'v': 460996268.0, 'vw': 141.5419, 'o': 137.11, 'c': 149.7, 'h': 150.01, 'l': 134.5933, 't': 1667707200000, 'n': 3602588}, {'v': 382679685.0, 'vw': 149.9923, 'o': 148.97, 'c': 151.29, 'h': 153.59, 'l': 146.15, 't': 1668315600000, 'n': 2830022}, {'v': 204007957.0, 'vw': 149.2673, 'o': 150.16, 'c': 148.11, 'h': 151.83, 'l': 146.925, 't': 1668920400000, 'n': 1673955}, {'v': 401087067.0, 'vw': 145.2495, 'o': 145.14, 'c': 147.81, 'h': 149.13, 'l': 140.355, 't': 1669525200000, 'n': 3025819}, {'v': 341487571.0, 'vw': 143.6699, 'o': 147.77, 'c': 142.16, 'h': 150.9199, 'l': 140, 't': 1670130000000, 'n': 2675844}, {'v': 504687504.0, 'vw': 140.2696, 'o': 142.7, 'c': 134.51, 'h': 149.9692, 'l': 133.73, 't': 1670734800000, 'n': 3497527}, {'v': 384450326.0, 'vw': 132.6461, 'o': 135.11, 'c': 131.86, 'h': 136.81, 'l': 129.64, 't': 1671339600000, 'n': 3119765}, {'v': 306152240.0, 'vw': 128.8925, 'o': 131.38, 'c': 129.93, 'h': 131.41, 'l': 125.87, 't': 1671944400000, 'n': 2561436}], 'status': 'OK', 'request_id': '2723a349169df5f2ecb206b5cb60b3c0', 'count': 53}

dict_keys(['ticker', 'queryCount', 'resultsCount', 'adjusted', 'results', 'status', 'request_id', 'count'])

In [26]:
DataSetApple= pd.DataFrame(Apple['results'])
DataSetApple.head(10)

,v,vw,o,c,h,l,t,n
0,339980123.0,179.0995,177.085,177.57,181.3300,177.07,1640494800000,2704014
1,481915611.0,177.1385,177.830,172.17,182.9400,171.03,1641099600000,4130315
2,422544574.0,173.0033,169.080,173.07,177.1800,168.17,1641704400000,3613640
3,400124342.0,167.1724,171.510,162.41,172.5400,162.30,1642309200000,3479982
4,688149428.0,161.9512,160.020,170.33,170.3500,154.70,1642914000000,6337774
5,457896933.0,173.6787,170.160,172.39,176.2399,169.51,1643518800000,3772842
6,412491545.0,172.9816,172.860,168.64,176.6500,168.04,1644123600000,3357351
7,363973562.0,169.7229,167.370,167.30,173.3400,166.19,1644728400000,3135169
8,414279367.0,161.6358,164.980,164.85,166.6900,152.00,1645333200000,3913514
9,418748277.0,164.8511,163.060,163.17,168.9100,161.97,1645938000000,3604858

In [27]:
#Microsoft
# Se lee un archivo .txt donde se encuentra el key privado de la API
with open("InfoIgnore/pass.txt",'r') as f:
    pwd= f.read()
# Se lee el API, se genera el requests y se descargan los datos de la API
url2 = "https://api.polygon.io/v2/aggs/ticker/MSFT/range/1/week/2022-01-01/2022-12-31?adjusted=true&sort=asc&apiKey="+pwd
headers2 = {"Accept-Encoding": "gzip, deflate"}
response2 = requests.get(url2, headers=headers2)
Microsoft = response2.json()
print(response2)
print(Microsoft)
Microsoft.keys()

<Response [200]>
{'ticker': 'MSFT', 'queryCount': 256, 'resultsCount': 53, 'adjusted': True, 'results': [{'v': 84640440.0, 'vw': 340.3078, 'o': 335.46, 'c': 336.32, 'h': 344.3, 'l': 335.43, 't': 1640494800000, 'n': 1196308}, {'v': 173985587.0, 'vw': 321.743, 'o': 335.35, 'c': 314.04, 'h': 338, 'l': 310.09, 't': 1641099600000, 'n': 2681567}, {'v': 193243449.0, 'vw': 311.8137, 'o': 309.485, 'c': 310.2, 'h': 323.41, 'l': 303.75, 't': 1641704400000, 'n': 2851966}, {'v': 181503045.0, 'vw': 304.4453, 'o': 304.07, 'c': 296.03, 'h': 313.9093, 'l': 295.61, 't': 1642309200000, 'n': 2778370}, {'v': 352527629.0, 'vw': 295.7335, 'o': 292.2, 'c': 308.26, 'h': 308.5, 'l': 276.05, 't': 1642914000000, 'n': 5049508}, {'v': 202854195.0, 'vw': 307.9229, 'o': 308.95, 'c': 305.94, 'h': 315.12, 'l': 299.96, 't': 1643518800000, 'n': 2852678}, {'v': 176675264.0, 'vw': 303.5428, 'o': 306.17, 'c': 295.04, 'h': 311.93, 'l': 294.22, 't': 1644123600000, 'n': 2518482}, {'v': 160418384.0, 'vw': 294.451, 'o': 293.77, 'c': 287.93, 'h': 300.87, 'l': 286.305, 't': 1644728400000, 'n': 2417687}, {'v': 169069691.0, 'vw': 287.695, 'o': 285, 'c': 297.31, 'h': 297.63, 'l': 271.52, 't': 1645333200000, 'n': 2583567}, {'v': 157402366.0, 'vw': 295.6795, 'o': 294.31, 'c': 289.86, 'h': 303.13, 'l': 287.165, 't': 1645938000000, 'n': 2401016}, {'v': 184356675.0, 'vw': 281.893, 'o': 288.53, 'c': 280.07, 'h': 289.69, 'l': 270, 't': 1646542800000, 'n': 2761895}, {'v': 176659719.0, 'vw': 289.716, 'o': 280.34, 'c': 300.43, 'h': 301, 'l': 275.82, 't': 1647147600000, 'n': 2327248}, {'v': 128717220.0, 'vw': 301.108, 'o': 298.89, 'c': 303.68, 'h': 305.5, 'l': 294.9, 't': 1647748800000, 'n': 1859691}, {'v': 148633495.0, 'vw': 310.8886, 'o': 304.33, 'c': 309.42, 'h': 315.95, 'l': 304.33, 't': 1648353600000, 'n': 1802049}, {'v': 143376031.0, 'vw': 304.2825, 'o': 310.09, 'c': 296.97, 'h': 315.11, 'l': 296.28, 't': 1648958400000, 'n': 1830930}, {'v': 115612021.0, 'vw': 285.062, 'o': 291.79, 'c': 279.83, 'h': 292.61, 'l': 279.32, 't': 1649563200000, 'n': 1610081}, {'v': 124808712.0, 'vw': 282.6097, 'o': 278.91, 'c': 274.03, 'h': 293.3, 'l': 273.38, 't': 1650168000000, 'n': 1791620}, {'v': 216379634.0, 'vw': 280.8744, 'o': 273.29, 'c': 277.52, 'h': 290.98, 'l': 270, 't': 1650772800000, 'n': 2957799}, {'v': 175740598.0, 'vw': 279.6073, 'o': 277.71, 'c': 274.73, 'h': 290.88, 'l': 271.27, 't': 1651377600000, 'n': 2444777}, {'v': 221990969.0, 'vw': 262.6451, 'o': 270.06, 'c': 261.12, 'h': 273.75, 'l': 250.02, 't': 1651982400000, 'n': 2978183}, {'v': 164581902.0, 'vw': 257.3368, 'o': 259.955, 'c': 252.56, 'h': 268.33, 'l': 246.44, 't': 1652587200000, 'n': 2090063}, {'v': 142680159.0, 'vw': 262.6314, 'o': 255.49, 'c': 273.24, 'h': 273.34, 'l': 253.43, 't': 1653192000000, 'n': 1689404}, {'v': 135180732.0, 'vw': 270.9324, 'o': 272.53, 'c': 270.02, 'h': 277.69, 'l': 261.6, 't': 1653796800000, 'n': 1520988}, {'v': 120515629.0, 'vw': 265.9607, 'o': 272.06, 'c': 252.99, 'h': 274.18, 'l': 252.53, 't': 1654401600000, 'n': 1502488}, {'v': 183927244.0, 'vw': 246.1803, 'o': 245.11, 'c': 247.65, 'h': 255.3, 'l': 241.51, 't': 1655006400000, 'n': 2231600}, {'v': 115659952.0, 'vw': 258.1221, 'o': 250.255, 'c': 267.7, 'h': 267.98, 'l': 249.51, 't': 1655611200000, 'n': 1289868}, {'v': 126613760.0, 'vw': 259.6237, 'o': 268.205, 'c': 259.58, 'h': 268.3, 'l': 252.9, 't': 1656216000000, 'n': 1542647}, {'v': 87299678.0, 'vw': 264.6872, 'o': 256.16, 'c': 267.66, 'h': 269.055, 'l': 254.74, 't': 1656820800000, 'n': 1177502}, {'v': 139718504.0, 'vw': 255.6888, 'o': 265.65, 'c': 256.72, 'h': 266.53, 'l': 245.94, 't': 1657425600000, 'n': 1714137}, {'v': 113061543.0, 'vw': 260.0712, 'o': 259.75, 'c': 260.36, 'h': 265.33, 'l': 253.3, 't': 1658030400000, 'n': 1378950}, {'v': 171963483.0, 'vw': 266.0981, 'o': 260.995, 'c': 280.74, 'h': 282, 'l': 249.57, 't': 1658635200000, 'n': 2081426}, {'v': 102685912.0, 'vw': 279.568, 'o': 277.82, 'c': 282.91, 'h': 283.8, 'l': 272.38, 't': 1659240000000, 'n': 1387593}, {'v': 109501514.0, 'vw': 286.1141, 'o': 284.05, 'c': 291.91, 'h': 291.91, 'l': 277.61, 't': 1659844800000, 'n': 1312488}, {'v': 91961619.0, 'vw': 290.6144, 'o': 291, 'c': 286.15, 'h': 294.18, 'l': 285.56, 't': 1660449600000, 'n': 1165437}, {'v': 104858212.0, 'vw': 275.7169, 'o': 282.08, 'c': 268.09, 'h': 282.46, 'l': 267.98, 't': 1661054400000, 'n': 1274741}, {'v': 113997760.0, 'vw': 261.6304, 'o': 265.85, 'c': 256.06, 'h': 267.4, 'l': 254.47, 't': 1661659200000, 'n': 1455394}, {'v': 87868043.0, 'vw': 258.1235, 'o': 256.2, 'c': 264.46, 'h': 265.23, 'l': 251.94, 't': 1662264000000, 'n': 1090979}, {'v': 147303078.0, 'vw': 251.0972, 'o': 265.78, 'c': 244.74, 'h': 267.45, 'l': 242.0627, 't': 1662868800000, 'n': 1766284}, {'v': 147296997.0, 'vw': 241.2099, 'o': 242.465, 'c': 237.92, 'h': 247.66, 'l': 235.2, 't': 1663473600000, 'n': 1777354}, {'v': 146583814.0, 'vw': 237.3405, 'o': 237.045, 'c': 232.9, 'h': 242.33, 'l': 232.73, 't': 1664078400000, 'n': 1607613}, {'v': 142036897.0, 'vw': 242.8727, 'o': 235.41, 'c': 234.24, 'h': 250.58, 'l': 233.17, 't': 1664683200000, 'n': 1596934}, {'v': 154871905.0, 'vw': 228.9184, 'o': 233.05, 'c': 228.56, 'h': 237.24, 'l': 219.13, 't': 1665288000000, 'n': 1821694}, {'v': 122568305.0, 'vw': 237.941, 'o': 235.82, 'c': 242.12, 'h': 243.93, 'l': 234.29, 't': 1665892800000, 'n': 1410731}, {'v': 223314152.0, 'vw': 235.9676, 'o': 243.76, 'c': 235.87, 'h': 251.04, 'l': 225.78, 't': 1666497600000, 'n': 2689040}, {'v': 170762758.0, 'vw': 223.7708, 'o': 233.76, 'c': 221.39, 'h': 235.74, 'l': 213.431, 't': 1667102400000, 'n': 2002457}, {'v': 170430629.0, 'vw': 234.2376, 'o': 221.99, 'c': 247.11, 'h': 247.99, 'l': 221.28, 't': 1667707200000, 'n': 1808509}, {'v': 137334196.0, 'vw': 241.9582, 'o': 241.985, 'c': 241.22, 'h': 247, 'l': 237.63, 't': 1668315600000, 'n': 1532607}, {'v': 74768133.0, 'vw': 244.505, 'o': 241.43, 'c': 247.49, 'h': 248.7, 'l': 240.71, 't': 1668920400000, 'n': 843148}, {'v': 137917867.0, 'vw': 248.8422, 'o': 246.08, 'c': 255.02, 'h': 256.12, 'l': 238.21, 't': 1669525200000, 'n': 1575223}, {'v': 109599743.0, 'vw': 246.9445, 'o': 252.01, 'c': 245.42, 'h': 253.819, 'l': 242.205, 't': 1670130000000, 'n': 1264469}, {'v': 229904423.0, 'vw': 251.1313, 'o': 247.445, 'c': 244.69, 'h': 263.915, 'l': 243.51, 't': 1670734800000, 'n': 2040071}, {'v': 128361491.0, 'vw': 240.0772, 'o': 244.86, 'c': 238.73, 'h': 245.615, 'l': 233.87, 't': 1671339600000, 'n': 1446589}, {'v': 75854917.0, 'vw': 238.2065, 'o': 238.7, 'c': 239.82, 'h': 241.92, 'l': 234.17, 't': 1671944400000, 'n': 911590}], 'status': 'OK', 'request_id': '328d20154d9ae7fc1e83e57c0a70bb19', 'count': 53}

dict_keys(['ticker', 'queryCount', 'resultsCount', 'adjusted', 'results', 'status', 'request_id', 'count'])

In [28]:
DataSetMicros= pd.DataFrame(Microsoft['results'])
DataSetMicros.head(10)

,v,vw,o,c,h,l,t,n
0,84640440.0,340.3078,335.460,336.32,344.3000,335.430,1640494800000,1196308
1,173985587.0,321.7430,335.350,314.04,338.0000,310.090,1641099600000,2681567
2,193243449.0,311.8137,309.485,310.20,323.4100,303.750,1641704400000,2851966
3,181503045.0,304.4453,304.070,296.03,313.9093,295.610,1642309200000,2778370
4,352527629.0,295.7335,292.200,308.26,308.5000,276.050,1642914000000,5049508
5,202854195.0,307.9229,308.950,305.94,315.1200,299.960,1643518800000,2852678
6,176675264.0,303.5428,306.170,295.04,311.9300,294.220,1644123600000,2518482
7,160418384.0,294.4510,293.770,287.93,300.8700,286.305,1644728400000,2417687
8,169069691.0,287.6950,285.000,297.31,297.6300,271.520,1645333200000,2583567
9,157402366.0,295.6795,294.310,289.86,303.1300,287.165,1645938000000,2401016

In [29]:
#Tesla
# Se lee un archivo .txt donde se encuentra el key privado de la API
with open("InfoIgnore/pass.txt",'r') as f:
    pwd= f.read()
# Se lee el API, se genera el requests y se descargan los datos de la API
url3 = "https://api.polygon.io/v2/aggs/ticker/TSLA/range/1/week/2022-01-01/2022-12-31?adjusted=true&sort=asc&apiKey="+pwd
headers3 = {"Accept-Encoding": "gzip, deflate"}
response3 = requests.get(url3, headers=headers3)
Tesla = response3.json()
print(response3)
print(Tesla)
Tesla.keys()

<Response [200]>
{'ticker': 'TSLA', 'queryCount': 256, 'resultsCount': 53, 'adjusted': True, 'results': [{'v': 274974996.0, 'vw': 362.2086, 'o': 357.89, 'c': 352.26, 'h': 373, 'l': 351.05, 't': 1640494800000, 'n': 2803036}, {'v': 458928342.0, 'vw': 371.7844, 'o': 382.5833, 'c': 342.32, 'h': 402.6667, 'l': 336.6667, 't': 1641099600000, 'n': 4730833}, {'v': 411424275.0, 'vw': 351.8286, 'o': 333.3333, 'c': 349.87, 'h': 371.8667, 'l': 326.6667, 't': 1641704400000, 'n': 4011889}, {'v': 315543468.0, 'vw': 334.9771, 'o': 342.2017, 'c': 314.6333, 'h': 356.93, 'l': 313.5, 't': 1642309200000, 'n': 3351290}, {'v': 624580770.0, 'vw': 295.0465, 'o': 301.5867, 'c': 282.1167, 'h': 329.23, 'l': 264.0033, 't': 1642914000000, 'n': 6822698}, {'v': 396660510.0, 'vw': 304.8763, 'o': 290.9033, 'c': 307.7733, 'h': 314.5667, 'l': 287.35, 't': 1643518800000, 'n': 3941622}, {'v': 309000771.0, 'vw': 303.8457, 'o': 307.93, 'c': 286.6667, 'h': 315.9233, 'l': 283.5667, 't': 1644123600000, 'n': 3301330}, {'v': 300106263.0, 'vw': 295.9868, 'o': 287.19, 'c': 285.66, 'h': 308.81, 'l': 279.2033, 't': 1644728400000, 'n': 3158118}, {'v': 389752218.0, 'vw': 262.5012, 'o': 278.0433, 'c': 269.9567, 'h': 285.5779, 'l': 233.3333, 't': 1645333200000, 'n': 4227756}, {'v': 377049954.0, 'vw': 285.7169, 'o': 271.67, 'c': 279.43, 'h': 296.6267, 'l': 271.5692, 't': 1645938000000, 'n': 3487290}, {'v': 337721757.0, 'vw': 275.8959, 'o': 285.4333, 'c': 265.1167, 'h': 288.7133, 'l': 260.7233, 't': 1646542800000, 'n': 3304792}, {'v': 388960950.0, 'vw': 277.8923, 'o': 260.2033, 'c': 301.7967, 'h': 302.6167, 'l': 252.0133, 't': 1647147600000, 'n': 3466112}, {'v': 439179402.0, 'vw': 327.2332, 'o': 304.9933, 'c': 336.88, 'h': 346.9, 'l': 302.3633, 't': 1647748800000, 'n': 4088075}, {'v': 339023172.0, 'vw': 362.7924, 'o': 355.0333, 'c': 361.53, 'h': 371.59, 'l': 351.2, 't': 1648353600000, 'n': 3596300}, {'v': 385665183.0, 'vw': 358.7082, 'o': 363.1267, 'c': 341.83, 'h': 384.29, 'l': 340.5134, 't': 1648958400000, 'n': 4035904}, {'v': 238851318.0, 'vw': 331.7819, 'o': 326.8, 'c': 328.3333, 'h': 342.08, 'l': 324.3657, 't': 1649563200000, 'n': 2474072}, {'v': 347221512.0, 'vw': 339.7329, 'o': 329.6767, 'c': 335.0167, 'h': 364.0733, 'l': 324.47, 't': 1650168000000, 'n': 3748353}, {'v': 494454384.0, 'vw': 301.7546, 'o': 326.3233, 'c': 290.2533, 'h': 336.2067, 'l': 273.9, 't': 1650772800000, 'n': 5464185}, {'v': 386474754.0, 'vw': 297.3939, 'o': 286.9233, 'c': 288.55, 'h': 318.5, 'l': 281.035, 't': 1651377600000, 'n': 3929641}, {'v': 503757648.0, 'vw': 255.9236, 'o': 278.8167, 'c': 256.53, 'h': 281.8767, 'l': 226.6667, 't': 1651982400000, 'n': 5431633}, {'v': 488765619.0, 'vw': 237.0838, 'o': 255.72, 'c': 221.3, 'h': 256.5867, 'l': 211, 't': 1652587200000, 'n': 4972410}, {'v': 464466348.0, 'vw': 226.4403, 'o': 218.34, 'c': 253.21, 'h': 253.2667, 'l': 206.8567, 't': 1653192000000, 'n': 4268178}, {'v': 385029189.0, 'vw': 248.992, 'o': 257.9467, 'c': 234.5167, 'h': 264.21, 'l': 233.4178, 't': 1653796800000, 'n': 3395538}, {'v': 427439094.0, 'vw': 240.1077, 'o': 244.3533, 'c': 232.23, 'h': 255.5466, 'l': 227.9133, 't': 1654401600000, 'n': 3927389}, {'v': 519391833.0, 'vw': 219.9656, 'o': 223.1667, 'c': 216.76, 'h': 235.6633, 'l': 208.6933, 't': 1655006400000, 'n': 4394851}, {'v': 423423588.0, 'vw': 238.5149, 'o': 224.6033, 'c': 245.7067, 'h': 246.8333, 'l': 224.3333, 't': 1655611200000, 'n': 3243752}, {'v': 431347923.0, 'vw': 232.7361, 'o': 249.3667, 'c': 227.2633, 'h': 252.07, 'l': 218.8633, 't': 1656216000000, 'n': 3580723}, {'v': 340417518.0, 'vw': 237.5617, 'o': 223, 'c': 250.7633, 'h': 254.98, 'l': 216.1667, 't': 1656820800000, 'n': 2911971}, {'v': 433621908.0, 'vw': 236.4575, 'o': 252.1033, 'c': 240.0667, 'h': 253.0633, 'l': 225.0333, 't': 1657425600000, 'n': 3457096}, {'v': 497409177.0, 'vw': 257.6774, 'o': 244.9367, 'c': 272.2433, 'h': 280.7867, 'l': 236.9767, 't': 1658030400000, 'n': 4110746}, {'v': 399040125.0, 'vw': 275.2257, 'o': 272.2167, 'c': 297.15, 'h': 298.32, 'l': 256.2633, 't': 1658635200000, 'n': 3268979}, {'v': 477595758.0, 'vw': 302.077, 'o': 301.275, 'c': 288.17, 'h': 313.6067, 'l': 285.5447, 't': 1659240000000, 'n': 4459373}, {'v': 430325859.0, 'vw': 291.6944, 'o': 295, 'c': 300.03, 'h': 305.2, 'l': 279.3533, 't': 1659844800000, 'n': 4024019}, {'v': 355092822.0, 'vw': 304.7483, 'o': 301.7867, 'c': 296.6667, 'h': 314.6667, 'l': 292.5, 't': 1660449600000, 'n': 3321378}, {'v': 287402927.0, 'vw': 294.4547, 'o': 291.9133, 'c': 288.09, 'h': 303.6467, 'l': 286.2967, 't': 1661054400000, 'n': 3783411}, {'v': 249666757.0, 'vw': 276.8911, 'o': 282.83, 'c': 270.21, 'h': 288.48, 'l': 266.15, 't': 1661659200000, 'n': 3873354}, {'v': 214045278.0, 'vw': 283.8681, 'o': 272.675, 'c': 299.68, 'h': 299.85, 'l': 265.74, 't': 1662264000000, 'n': 3064757}, {'v': 341338685.0, 'vw': 300.4843, 'o': 300.72, 'c': 303.35, 'h': 309.12, 'l': 290.4, 't': 1662868800000, 'n': 4316932}, {'v': 318559667.0, 'vw': 297.9454, 'o': 300.09, 'c': 275.33, 'h': 313.8, 'l': 272.82, 't': 1663473600000, 'n': 4643100}, {'v': 319712247.0, 'vw': 276.5234, 'o': 271.83, 'c': 265.25, 'h': 289, 'l': 262.47, 't': 1664078400000, 'n': 4559722}, {'v': 447689986.0, 'vw': 240.6205, 'o': 254.5, 'c': 223.07, 'h': 257.5, 'l': 222.02, 't': 1664683200000, 'n': 6098159}, {'v': 397042775.0, 'vw': 216.946, 'o': 223.93, 'c': 204.99, 'h': 226.99, 'l': 204.16, 't': 1665288000000, 'n': 5067182}, {'v': 414060604.0, 'vw': 214.7463, 'o': 210.04, 'c': 214.44, 'h': 229.82, 'l': 202, 't': 1665892800000, 'n': 5110254}, {'v': 412656079.0, 'vw': 219.5027, 'o': 205.82, 'c': 228.52, 'h': 233.81, 'l': 198.5863, 't': 1666497600000, 'n': 4814572}, {'v': 342460436.0, 'vw': 220.3754, 'o': 226.19, 'c': 207.47, 'h': 237.3951, 'l': 203.08, 't': 1667102400000, 'n': 4068509}, {'v': 596782669.0, 'vw': 190.4748, 'o': 208.65, 'c': 195.97, 'h': 208.9, 'l': 177.12, 't': 1667707200000, 'n': 7039741}, {'v': 390185620.0, 'vw': 188.5378, 'o': 192.77, 'c': 180.19, 'h': 200.8237, 'l': 176.55, 't': 1668315600000, 'n': 4466435}, {'v': 331480237.0, 'vw': 175.104, 'o': 175.85, 'c': 182.86, 'h': 185.2, 'l': 166.185, 't': 1668920400000, 'n': 3895214}, {'v': 438857098.0, 'vw': 188.3635, 'o': 179.96, 'c': 194.86, 'h': 198.92, 'l': 178.75, 't': 1669525200000, 'n': 4531220}, {'v': 471866551.0, 'vw': 177.887, 'o': 189.44, 'c': 179.05, 'h': 191.27, 'l': 169.06, 't': 1670130000000, 'n': 5152139}, {'v': 687178265.0, 'vw': 160.2206, 'o': 176.1, 'c': 150.23, 'h': 177.37, 'l': 150.04, 't': 1670734800000, 'n': 7323036}, {'v': 821234763.0, 'vw': 135.6839, 'o': 154, 'c': 123.15, 'h': 155.25, 'l': 121.02, 't': 1671339600000, 'n': 7937949}, {'v': 809277583.0, 'vw': 116.6789, 'o': 117.495, 'c': 123.18, 'h': 124.48, 'l': 108.24, 't': 1671944400000, 'n': 7512885}], 'status': 'OK', 'request_id': '7b21abe721e5f56d0a545701162b705e', 'count': 53}

dict_keys(['ticker', 'queryCount', 'resultsCount', 'adjusted', 'results', 'status', 'request_id', 'count'])

In [30]:
DataSetTesla= pd.DataFrame(Tesla['results'])
DataSetTesla.head(10)

,v,vw,o,c,h,l,t,n
0,274974996.0,362.2086,357.8900,352.2600,373.0000,351.0500,1640494800000,2803036
1,458928342.0,371.7844,382.5833,342.3200,402.6667,336.6667,1641099600000,4730833
2,411424275.0,351.8286,333.3333,349.8700,371.8667,326.6667,1641704400000,4011889
3,315543468.0,334.9771,342.2017,314.6333,356.9300,313.5000,1642309200000,3351290
4,624580770.0,295.0465,301.5867,282.1167,329.2300,264.0033,1642914000000,6822698
5,396660510.0,304.8763,290.9033,307.7733,314.5667,287.3500,1643518800000,3941622
6,309000771.0,303.8457,307.9300,286.6667,315.9233,283.5667,1644123600000,3301330
7,300106263.0,295.9868,287.1900,285.6600,308.8100,279.2033,1644728400000,3158118
8,389752218.0,262.5012,278.0433,269.9567,285.5779,233.3333,1645333200000,4227756
9,377049954.0,285.7169,271.6700,279.4300,296.6267,271.5692,1645938000000,3487290

In [31]:
#NVIDIA
# Se lee un archivo .txt donde se encuentra el key privado de la API
with open("InfoIgnore/pass.txt",'r') as f:
    pwd= f.read()
# Se lee el API, se genera el requests y se descargan los datos de la API
url4 = "https://api.polygon.io/v2/aggs/ticker/NVDA/range/1/week/2022-01-01/2022-12-31?adjusted=true&sort=asc&apiKey="+pwd
headers4 = {"Accept-Encoding": "gzip, deflate"}
response4 = requests.get(url4, headers=headers4)
NVIDIA = response4.json()
print(response4)
print(NVIDIA)
NVIDIA.keys()

<Response [200]>
{'ticker': 'NVDA', 'queryCount': 256, 'resultsCount': 53, 'adjusted': True, 'results': [{'v': 174121048.0, 'vw': 301.957, 'o': 296.6, 'c': 294.11, 'h': 313.3, 'l': 293.3057, 't': 1640494800000, 'n': 2489136}, {'v': 228174609.0, 'vw': 285.9871, 'o': 298.15, 'c': 272.47, 'h': 307.11, 'l': 270.57, 't': 1641099600000, 'n': 3681603}, {'v': 231652947.0, 'vw': 271.1252, 'o': 265.81, 'c': 269.42, 'h': 285.95, 'l': 256.4384, 't': 1641704400000, 'n': 3591545}, {'v': 206775925.0, 'vw': 249.5387, 'o': 262.6, 'c': 233.74, 'h': 266.38, 'l': 232.63, 't': 1642309200000, 'n': 3227924}, {'v': 345310535.0, 'vw': 224.7878, 'o': 223.3, 'c': 228.4, 'h': 240.57, 'l': 208.88, 't': 1642914000000, 'n': 5111249}, {'v': 239051704.0, 'vw': 244.4144, 'o': 231.82, 'c': 243.19, 'h': 258.17, 'l': 230.52, 't': 1643518800000, 'n': 3320679}, {'v': 242835250.0, 'vw': 253.7967, 'o': 243.72, 'c': 239.49, 'h': 269.2499, 'l': 237.73, 't': 1644123600000, 'n': 3541710}, {'v': 344245354.0, 'vw': 250.1017, 'o': 239.34, 'c': 236.42, 'h': 265.82, 'l': 231, 't': 1644728400000, 'n': 4874223}, {'v': 246438235.0, 'vw': 231.5662, 'o': 230.35, 'c': 241.57, 'h': 242.17, 'l': 208.9, 't': 1645333200000, 'n': 3333658}, {'v': 207606593.0, 'vw': 237.2924, 'o': 239.92, 'c': 229.36, 'h': 246.65, 'l': 224.82, 't': 1645938000000, 'n': 2833030}, {'v': 229605425.0, 'vw': 221.9075, 'o': 228.17, 'c': 221, 'h': 232.2, 'l': 206.5, 't': 1646542800000, 'n': 3157282}, {'v': 274679442.0, 'vw': 240.1464, 'o': 218.69, 'c': 264.53, 'h': 265.6899, 'l': 211.5901, 't': 1647147600000, 'n': 3359669}, {'v': 309672586.0, 'vw': 269.9759, 'o': 265.07, 'c': 276.92, 'h': 283.58, 'l': 255.7501, 't': 1647748800000, 'n': 3991432}, {'v': 241809078.0, 'vw': 277.1265, 'o': 277.555, 'c': 267.12, 'h': 289.46, 'l': 262.67, 't': 1648353600000, 'n': 3257568}, {'v': 261778582.0, 'vw': 249.1499, 'o': 267.28, 'c': 231.19, 'h': 275.58, 'l': 230.6201, 't': 1648958400000, 'n': 3513416}, {'v': 231832270.0, 'vw': 218.9992, 'o': 222.14, 'c': 212.58, 'h': 227.77, 'l': 211.63, 't': 1649563200000, 'n': 3254642}, {'v': 278764850.0, 'vw': 211.3755, 'o': 212, 'c': 195.15, 'h': 226.7037, 'l': 195, 't': 1650168000000, 'n': 3768579}, {'v': 286484250.0, 'vw': 191.3893, 'o': 192.02, 'c': 185.47, 'h': 201.2848, 'l': 182.9, 't': 1650772800000, 'n': 3346908}, {'v': 295052228.0, 'vw': 191.2856, 'o': 185.405, 'c': 186.75, 'h': 204, 'l': 179.9, 't': 1651377600000, 'n': 3315552}, {'v': 344444307.0, 'vw': 171.3399, 'o': 180.34, 'c': 177.06, 'h': 182.55, 'l': 155.67, 't': 1651982400000, 'n': 4029039}, {'v': 301285160.0, 'vw': 172.4672, 'o': 175.09, 'c': 166.94, 'h': 183.71, 'l': 157.55, 't': 1652587200000, 'n': 2855758}, {'v': 374274327.0, 'vw': 171.4299, 'o': 162.74, 'c': 188.11, 'h': 188.81, 'l': 157.8, 't': 1653192000000, 'n': 3488852}, {'v': 245592391.0, 'vw': 188.4936, 'o': 189.8, 'c': 187.2, 'h': 196.19, 'l': 181.22, 't': 1653796800000, 'n': 2322268}, {'v': 203569617.0, 'vw': 183.7727, 'o': 191.39, 'c': 169.74, 'h': 193.37, 'l': 168.69, 't': 1654401600000, 'n': 2108622}, {'v': 281280619.0, 'vw': 158.7496, 'o': 160, 'c': 158.8, 'h': 168.68, 'l': 153.28, 't': 1655006400000, 'n': 2804555}, {'v': 185690124.0, 'vw': 165.5791, 'o': 164.745, 'c': 171.26, 'h': 171.4, 'l': 158.53, 't': 1655611200000, 'n': 1904213}, {'v': 263567363.0, 'vw': 156.027, 'o': 173.12, 'c': 145.23, 'h': 173.3, 'l': 143.92, 't': 1656216000000, 'n': 2736022}, {'v': 214214799.0, 'vw': 152.2421, 'o': 141.75, 'c': 158.38, 'h': 160.3699, 'l': 140.55, 't': 1656820800000, 'n': 1966982}, {'v': 225991548.0, 'vw': 152.1521, 'o': 155.26, 'c': 157.62, 'h': 157.82, 'l': 144.65, 't': 1657425600000, 'n': 2159498}, {'v': 322712578.0, 'vw': 171.8835, 'o': 163.02, 'c': 173.19, 'h': 181.44, 'l': 160.02, 't': 1658030400000, 'n': 3101501}, {'v': 235849535.0, 'vw': 173.9439, 'o': 170.19, 'c': 181.63, 'h': 182.44, 'l': 164.78, 't': 1658635200000, 'n': 2324689}, {'v': 217963709.0, 'vw': 187.0486, 'o': 181.82, 'c': 189.89, 'h': 192.74, 'l': 179.9, 't': 1659240000000, 'n': 2256379}, {'v': 323675779.0, 'vw': 177.7492, 'o': 175.02, 'c': 187.09, 'h': 187.18, 'l': 167.24, 't': 1659844800000, 'n': 3289407}, {'v': 221234320.0, 'vw': 185.4276, 'o': 187.01, 'c': 178.49, 'h': 191.64, 'l': 177.7, 't': 1660449600000, 'n': 2105928}, {'v': 284198095.0, 'vw': 172.0312, 'o': 174.9, 'c': 162.6, 'h': 179.47, 'l': 162.37, 't': 1661054400000, 'n': 2723811}, {'v': 351900259.0, 'vw': 145.5485, 'o': 160.2, 'c': 136.47, 'h': 163.38, 'l': 132.7021, 't': 1661659200000, 'n': 3607971}, {'v': 215946018.0, 'vw': 138.0501, 'o': 137.31, 'c': 143.87, 'h': 144.74, 'l': 133.46, 't': 1662264000000, 'n': 1847789}, {'v': 298130597.0, 'vw': 133.3711, 'o': 143.69, 'c': 131.98, 'h': 145.47, 'l': 126.17, 't': 1662868800000, 'n': 2819070}, {'v': 332260790.0, 'vw': 130.1786, 'o': 130.12, 'c': 125.16, 'h': 140.31, 'l': 122.57, 't': 1663473600000, 'n': 2720455}, {'v': 274121817.0, 'vw': 124.0454, 'o': 124.91, 'c': 121.39, 'h': 128.23, 'l': 119.4601, 't': 1664078400000, 'n': 2290050}, {'v': 295497842.0, 'vw': 128.18, 'o': 123.47, 'c': 120.76, 'h': 136.56, 'l': 120.22, 't': 1664683200000, 'n': 2312106}, {'v': 342196307.0, 'vw': 115.6672, 'o': 120.37, 'c': 112.27, 'h': 121.2432, 'l': 108.13, 't': 1665288000000, 'n': 2621423}, {'v': 302453386.0, 'vw': 121.0946, 'o': 115.18, 'c': 124.66, 'h': 127.69, 'l': 115.17, 't': 1665892800000, 'n': 2177094}, {'v': 266238603.0, 'vw': 131.2521, 'o': 125.08, 'c': 138.34, 'h': 138.5, 'l': 120.64, 't': 1666497600000, 'n': 2274417}, {'v': 270442650.0, 'vw': 136.9847, 'o': 137.78, 'c': 141.56, 'h': 142.29, 'l': 129.56, 't': 1667102400000, 'n': 2270068}, {'v': 281595876.0, 'vw': 149.339, 'o': 142.28, 'c': 163.27, 'h': 163.89, 'l': 137.5901, 't': 1667707200000, 'n': 2567880}, {'v': 292624000.0, 'vw': 160.8383, 'o': 162.18, 'c': 154.09, 'h': 169.98, 'l': 151.2001, 't': 1668315600000, 'n': 2513030}, {'v': 147261061.0, 'vw': 158.62, 'o': 151.47, 'c': 162.7, 'h': 165.27, 'l': 150.8, 't': 1668920400000, 'n': 1236219}, {'v': 201007987.0, 'vw': 164.2249, 'o': 160.26, 'c': 168.76, 'h': 172.65, 'l': 155.2, 't': 1669525200000, 'n': 1977646}, {'v': 205813075.0, 'vw': 166.187, 'o': 166.79, 'c': 170.01, 'h': 175.83, 'l': 156.67, 't': 1670130000000, 'n': 2170950}, {'v': 256618069.0, 'vw': 174.286, 'o': 170.37, 'c': 165.71, 'h': 187.9, 'l': 164.1, 't': 1670734800000, 'n': 2742642}, {'v': 199612484.0, 'vw': 158.0361, 'o': 165.72, 'c': 152.06, 'h': 166.27, 'l': 148.82, 't': 1671339600000, 'n': 1883069}, {'v': 148138178.0, 'vw': 143.6469, 'o': 150.74, 'c': 146.14, 'h': 151, 'l': 138.84, 't': 1671944400000, 'n': 1350528}], 'status': 'OK', 'request_id': 'ae96bd66d52f4e1bab7f6848a45cf39c', 'count': 53}

dict_keys(['ticker', 'queryCount', 'resultsCount', 'adjusted', 'results', 'status', 'request_id', 'count'])

In [32]:
DataSetNVIDIA= pd.DataFrame(NVIDIA['results'])
DataSetNVIDIA.head(10)

,v,vw,o,c,h,l,t,n
0,174121048.0,301.9570,296.60,294.11,313.3000,293.3057,1640494800000,2489136
1,228174609.0,285.9871,298.15,272.47,307.1100,270.5700,1641099600000,3681603
2,231652947.0,271.1252,265.81,269.42,285.9500,256.4384,1641704400000,3591545
3,206775925.0,249.5387,262.60,233.74,266.3800,232.6300,1642309200000,3227924
4,345310535.0,224.7878,223.30,228.40,240.5700,208.8800,1642914000000,5111249
5,239051704.0,244.4144,231.82,243.19,258.1700,230.5200,1643518800000,3320679
6,242835250.0,253.7967,243.72,239.49,269.2499,237.7300,1644123600000,3541710
7,344245354.0,250.1017,239.34,236.42,265.8200,231.0000,1644728400000,4874223
8,246438235.0,231.5662,230.35,241.57,242.1700,208.9000,1645333200000,3333658
9,207606593.0,237.2924,239.92,229.36,246.6500,224.8200,1645938000000,2833030

In [35]:
#Intel
# Se lee un archivo .txt donde se encuentra el key privado de la API
with open("InfoIgnore/pass.txt",'r') as f:
    pwd= f.read()
# Se lee el API, se genera el requests y se descargan los datos de la API
url5 = "https://api.polygon.io/v2/aggs/ticker/INTC/range/1/week/2022-01-01/2022-12-31?adjusted=true&sort=asc&apiKey="+pwd
headers5 = {"Accept-Encoding": "gzip, deflate"}
response5 = requests.get(url5, headers=headers5)
Intel = response5.json()
print(response5)
print(Intel)
Intel.keys()

<Response [200]>
{'ticker': 'INTC', 'queryCount': 256, 'resultsCount': 53, 'adjusted': True, 'results': [{'v': 89134260.0, 'vw': 51.7927, 'o': 51.35, 'c': 51.5, 'h': 52.159, 'l': 51.3022, 't': 1640494800000, 'n': 523343}, {'v': 205104738.0, 'vw': 53.836, 'o': 51.65, 'c': 53.44, 'h': 56.17, 'l': 51.6, 't': 1641099600000, 'n': 1217901}, {'v': 177949685.0, 'vw': 55.2481, 'o': 53.97, 'c': 55.7, 'h': 56.28, 'l': 53.31, 't': 1641704400000, 'n': 1169236}, {'v': 140882681.0, 'vw': 53.5051, 'o': 55.31, 'c': 52.04, 'h': 55.65, 'l': 51.94, 't': 1642309200000, 'n': 908946}, {'v': 314741764.0, 'vw': 49.6664, 'o': 51.48, 'c': 47.73, 'h': 52.72, 'l': 46.3, 't': 1642914000000, 'n': 2188581}, {'v': 196746037.0, 'vw': 48.5167, 'o': 47.68, 'c': 48.01, 'h': 49.685, 'l': 47.13, 't': 1643518800000, 'n': 1192794}, {'v': 160708423.0, 'vw': 48.7809, 'o': 48.13, 'c': 47.63, 'h': 49.97, 'l': 47.5, 't': 1644123600000, 'n': 958998}, {'v': 198737619.0, 'vw': 46.8105, 'o': 47.92, 'c': 45.04, 'h': 48.49, 'l': 44.51, 't': 1644728400000, 'n': 1289804}, {'v': 207242835.0, 'vw': 45.4989, 'o': 44.69, 'c': 47.71, 'h': 47.79, 'l': 43.625, 't': 1645333200000, 'n': 1290645}, {'v': 217450476.0, 'vw': 47.6649, 'o': 47, 'c': 48.07, 'h': 48.99, 'l': 46.22, 't': 1645938000000, 'n': 1322147}, {'v': 188214197.0, 'vw': 47.2978, 'o': 48.005, 'c': 45.83, 'h': 48.72, 'l': 45.765, 't': 1646542800000, 'n': 1175717}, {'v': 184120391.0, 'vw': 45.967, 'o': 45.9, 'c': 47.45, 'h': 47.6, 'l': 44.07, 't': 1647147600000, 'n': 1083588}, {'v': 182888044.0, 'vw': 49.4708, 'o': 47.46, 'c': 51.83, 'h': 51.9783, 'l': 47.065, 't': 1647748800000, 'n': 1133127}, {'v': 164714048.0, 'vw': 50.2188, 'o': 51.36, 'c': 48.11, 'h': 52.51, 'l': 47.325, 't': 1648353600000, 'n': 1061554}, {'v': 127393471.0, 'vw': 47.8805, 'o': 48.17, 'c': 47.02, 'h': 49.23, 'l': 46.77, 't': 1648958400000, 'n': 873226}, {'v': 118266970.0, 'vw': 46.6018, 'o': 46.9, 'c': 45.67, 'h': 47.91, 'l': 45.62, 't': 1649563200000, 'n': 715406}, {'v': 135400048.0, 'vw': 47.4341, 'o': 45.53, 'c': 46.54, 'h': 48.9, 'l': 45.52, 't': 1650168000000, 'n': 831983}, {'v': 211525799.0, 'vw': 45.4503, 'o': 46.21, 'c': 43.59, 'h': 47.27, 'l': 43.5, 't': 1650772800000, 'n': 1409380}, {'v': 220696229.0, 'vw': 44.857, 'o': 43.72, 'c': 44.3, 'h': 46.64, 'l': 43.51, 't': 1651377600000, 'n': 1448677}, {'v': 202352548.0, 'vw': 43.3305, 'o': 43.81, 'c': 43.6, 'h': 44.735, 'l': 42.01, 't': 1651982400000, 'n': 1338523}, {'v': 162829070.0, 'vw': 42.5313, 'o': 43.42, 'c': 41.65, 'h': 44.42, 'l': 40.31, 't': 1652587200000, 'n': 1067609}, {'v': 142700360.0, 'vw': 42.6388, 'o': 41.69, 'c': 44.55, 'h': 44.55, 'l': 41.1, 't': 1653192000000, 'n': 865854}, {'v': 132639314.0, 'vw': 44.1779, 'o': 44.25, 'c': 43.39, 'h': 44.93, 'l': 43.34, 't': 1653796800000, 'n': 731878}, {'v': 192275076.0, 'vw': 41.3466, 'o': 43.81, 'c': 39.18, 'h': 44.04, 'l': 39.18, 't': 1654401600000, 'n': 1185046}, {'v': 236290136.0, 'vw': 37.6662, 'o': 38.55, 'c': 36.97, 'h': 39.17, 'l': 36.6, 't': 1655006400000, 'n': 1271191}, {'v': 134919288.0, 'vw': 37.775, 'o': 37.36, 'c': 38.61, 'h': 38.64, 'l': 36.91, 't': 1655611200000, 'n': 704754}, {'v': 168602587.0, 'vw': 37.5207, 'o': 38.87, 'c': 36.34, 'h': 39.06, 'l': 35.88, 't': 1656216000000, 'n': 976565}, {'v': 115135950.0, 'vw': 37.2216, 'o': 35.93, 'c': 37.99, 'h': 38.33, 'l': 35.54, 't': 1656820800000, 'n': 714710}, {'v': 153106683.0, 'vw': 37.4839, 'o': 37.66, 'c': 38.62, 'h': 38.67, 'l': 36.29, 't': 1657425600000, 'n': 851200}, {'v': 191308724.0, 'vw': 39.8436, 'o': 39.1, 'c': 39.2, 'h': 40.73, 'l': 38.525, 't': 1658030400000, 'n': 1028388}, {'v': 292649155.0, 'vw': 37.8598, 'o': 39.285, 'c': 36.31, 'h': 40.425, 'l': 35.24, 't': 1658635200000, 'n': 1461095}, {'v': 260208022.0, 'vw': 36.1005, 'o': 36.05, 'c': 35.39, 'h': 37.69, 'l': 35.18, 't': 1659240000000, 'n': 1347589}, {'v': 204822102.0, 'vw': 35.3497, 'o': 35.36, 'c': 36.11, 'h': 36.29, 'l': 34.4, 't': 1659844800000, 'n': 1043224}, {'v': 135441808.0, 'vw': 35.8875, 'o': 36.1, 'c': 35.38, 'h': 36.575, 'l': 35.19, 't': 1660449600000, 'n': 724341}, {'v': 181449502.0, 'vw': 34.0512, 'o': 35, 'c': 33.36, 'h': 35.06, 'l': 33.35, 't': 1661054400000, 'n': 892846}, {'v': 188567666.0, 'vw': 32.09, 'o': 33.225, 'c': 31.22, 'h': 33.41, 'l': 31.06, 't': 1661659200000, 'n': 1000251}, {'v': 155591087.0, 'vw': 30.7176, 'o': 31.39, 'c': 31.46, 'h': 31.5, 'l': 29.91, 't': 1662264000000, 'n': 823714}, {'v': 263128611.0, 'vw': 29.626, 'o': 31.735, 'c': 29.24, 'h': 31.86, 'l': 28.42, 't': 1662868800000, 'n': 1220065}, {'v': 183841952.0, 'vw': 28.5117, 'o': 29.02, 'c': 27.52, 'h': 29.59, 'l': 27.19, 't': 1663473600000, 'n': 970368}, {'v': 214922956.0, 'vw': 26.7132, 'o': 27.56, 'c': 25.77, 'h': 27.6995, 'l': 25.74, 't': 1664078400000, 'n': 1029647}, {'v': 207844266.0, 'vw': 26.8899, 'o': 26.33, 'c': 25.72, 'h': 27.84, 'l': 25.651, 't': 1664683200000, 'n': 988647}, {'v': 241810735.0, 'vw': 25.5904, 'o': 25.94, 'c': 25.91, 'h': 26.835, 'l': 24.59, 't': 1665288000000, 'n': 1148432}, {'v': 210731999.0, 'vw': 26.2741, 'o': 26.31, 'c': 26.97, 'h': 27.05, 'l': 25.54, 't': 1665892800000, 'n': 931850}, {'v': 261104640.0, 'vw': 27.6453, 'o': 26.75, 'c': 29.07, 'h': 29.2186, 'l': 26.13, 't': 1666497600000, 'n': 1304020}, {'v': 238612689.0, 'vw': 28.1239, 'o': 29.08, 'c': 28.2, 'h': 29.18, 'l': 27.17, 't': 1667102400000, 'n': 1160440}, {'v': 213961933.0, 'vw': 28.9642, 'o': 28.36, 'c': 30.43, 'h': 30.63, 'l': 27.52, 't': 1667707200000, 'n': 984077}, {'v': 174994261.0, 'vw': 30.1886, 'o': 30.34, 'c': 29.87, 'h': 31.335, 'l': 29, 't': 1668315600000, 'n': 837818}, {'v': 96129576.0, 'vw': 29.4121, 'o': 29.66, 'c': 29.34, 'h': 30.08, 'l': 28.91, 't': 1668920400000, 'n': 472436}, {'v': 195158405.0, 'vw': 29.3463, 'o': 29.1, 'c': 29.41, 'h': 30.48, 'l': 28.22, 't': 1669525200000, 'n': 871499}, {'v': 144108943.0, 'vw': 28.6614, 'o': 29.42, 'c': 28.24, 'h': 29.75, 'l': 28.065, 't': 1670130000000, 'n': 718627}, {'v': 257592665.0, 'vw': 27.8411, 'o': 28.13, 'c': 26.92, 'h': 30.09, 'l': 26.4522, 't': 1670734800000, 'n': 1010297}, {'v': 168705864.0, 'vw': 26.3492, 'o': 26.9, 'c': 26.09, 'h': 26.97, 'l': 25.35, 't': 1671339600000, 'n': 754379}, {'v': 117699898.0, 'vw': 26.0017, 'o': 25.845, 'c': 26.43, 'h': 26.46, 'l': 25.5, 't': 1671944400000, 'n': 552426}], 'status': 'OK', 'request_id': '39918f9b6aa2f06e6f66281c3b0e72c1', 'count': 53}

dict_keys(['ticker', 'queryCount', 'resultsCount', 'adjusted', 'results', 'status', 'request_id', 'count'])

In [36]:
DataSetIntel= pd.DataFrame(Intel['results'])
DataSetIntel.head(10)

             v       vw      o      c       h        l              t        n
0   89134260.0  51.7927  51.35  51.50  52.159  51.3022  1640494800000   523343
1  205104738.0  53.8360  51.65  53.44  56.170  51.6000  1641099600000  1217901
2  177949685.0  55.2481  53.97  55.70  56.280  53.3100  1641704400000  1169236
3  140882681.0  53.5051  55.31  52.04  55.650  51.9400  1642309200000   908946
4  314741764.0  49.6664  51.48  47.73  52.720  46.3000  1642914000000  2188581
5  196746037.0  48.5167  47.68  48.01  49.685  47.1300  1643518800000  1192794
6  160708423.0  48.7809  48.13  47.63  49.970  47.5000  1644123600000   958998
7  198737619.0  46.8105  47.92  45.04  48.490  44.5100  1644728400000  1289804
8  207242835.0  45.4989  44.69  47.71  47.790  43.6250  1645333200000  1290645
9  217450476.0  47.6649  47.00  48.07  48.990  46.2200  1645938000000  1322147